
loopback_ip: 1.1.1.11

underlay:
    local:
        asn: 60011
    neighbors:
      - interface: xe-0/0/0
        name: spine1
        asn: 60001
        peer_ip: "{{ p2p.link1.1 }}"
        local_ip: "{{ p2p.link1.2 }}"
      - interface: xe-0/0/1
        name: spine2
        asn: 60002
        peer_ip: "{{ p2p.link2.1 }}"
        local_ip: "{{ p2p.link2.2 }}"

junos_std_l3:
    - name: xe-0/0/2
      units:
      - id: 0
        ip: 192.168.1.1
        mask: 24
