host_name: spine1
host:
  local_as: 65001
  loopback:
    ip_address: 1.1.1.1/32
  interfaces:
    - interface: xe-0/0/0
      description: leaf1
      mtu: 9216
      units:
        - number: 0
          mtu: 9100
          ip_address: 10.10.1.0/31
    - interface: xe-0/0/1
      description: leaf2
      mtu: 9216
      units:
        - number: 0
          mtu: 9100
          ip_address: 10.10.1.2/31
    - interface: xe-0/0/2
      description: leaf3
      mtu: 9216
      units:
        - number: 0
          mtu: 9100
          ip_address: 10.10.1.4/31
  protocols:
    bgp:
      groups:
        - name: fabric
          type: external
          neighbors:
            - name: 10.10.1.1
              peer_as: 65003
            - name: 10.10.1.3
              peer_as: 65004
            - name: 10.10.1.5
              peer_as: 65005
    pim:
      rp: 10.10.10.10
      anycast_rp: 2.2.2.2
      interfaces:
        - name: xe-0/0/0.0
          mode: sparse
        - name: xe-0/0/1.0
          mode: sparse
          name: xe-0/0/2.0
          mode: sparse