host_name: leaf3
host:
  local_as: 65000
  loopback:
    ip_address: 5.5.5.5/32
  route_distinguisher: "5555:1"
  vrf_target: "target:65000:5555"
  interfaces:
    - interface: xe-0/0/0
      description: spine1
      family: inet
      units:
        - number: 0
          ip_address: 10.10.1.5/31
    - interface: xe-0/0/1
      description: spine2
      family: inet
      units:
        - number: 0
          ip_address: 10.10.2.5/31
    - interface: xe-0/0/2
      description: vSRX
      family: ethernet-switching
      units:
        - number: 0
          mode: trunk
          vlans: 
            - HOST1TEST
	    - HOST2TEST
  protocols:
    bgp:
      groups:
        - name: overlay
          type: internal
          neighbors:
            - name: 3.3.3.3
              peer_as: 65003
            - name: 4.4.4.4
              peer_as: 65004
    ospf:
      interfaces:
        - xe-0/0/0
        - xe-0/0/1
        - lo0.0
  vlans:
    - name: HOST1TEST
      vlan_id: 100
      vni: 1000
    - name: HOST2TEST
      vlan_id: 200
      vni: 2000

