
loopback_ip: 1.1.1.13

underlay:
    local:
        asn: 60013
    neighbors:
      - interface: xe-0/0/0
        name: spine1
        asn: 60001
        peer_ip: "{{ p2p.link5.1 }}"
        local_ip: "{{ p2p.link5.2 }}"
      - interface: xe-0/0/1
        name: spine2
        asn: 60002
        peer_ip: "{{ p2p.link6.1 }}"
        local_ip: "{{ p2p.link6.2 }}"

junos_std_l3:
    - name: xe-0/0/2
      units:
      - id: 0
        ip: 192.168.3.1
        mask: 24
