- name: Build base configuration
  hosts: spine
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - debug:
        var: hostvars[inventory_hostname]
    - name: Build Base Configuration
      template: src=templates/spine.xml dest=/tmp/{{ inventory_hostname  }}.xml

    - name: Install template
      junos_install_config:
        host: "{{ ansible_ssh_host  }}"
        port: "{{ ansible_ssh_port  }}"
        user: "root"
        passwd: "Juniper"
        comment: "configured by ansible"
        file: "/tmp/{{ inventory_hostname  }}.xml"
        logfile: "changes.log"
        replace: true

