host_name: leaf2
host:
  local_as: 65004
  loopback:
    ip_address: 4.4.4.4/32
  interfaces:
    - interface: xe-0/0/0
      description: spine1
      family: inet
      mtu: 9216
      units:
        - number: 0
          mtu: 9100
          ip_address: 10.10.1.3/31
    - interface: xe-0/0/1
      description: spine2
      family: inet
      mtu: 9216
      units:
        - number: 0
          mtu: 9100
          ip_address: 10.10.2.3/31
    - interface: xe-0/0/2
      description: HOST2
      family: ethernet-switching
      mtu: 9216
      units:
        - number: 0
          mode: trunk
          # this is fine for now, but make it an array
          # later on
          vlans: HOST1TEST
  protocols:
    bgp:
      groups:
        - name: fabric
          type: external
          neighbors:
            - name: 10.10.1.2
              peer_as: 65001
            - name: 10.10.2.2
              peer_as: 65002
    pim:
      rp_address: 1.1.1.1
  vlans:
    - name: HOST1TEST
      vlan_id: 100
      vni: 1000
      multicast_group: 225.10.10.10
    - name: HOST2TEST
      vlan_id: 200
      vni: 2000
      multicast_group: 225.10.10.10
