version: "3"

services:
    eidetic-gdb:
        image: neo4j:latest
        ports:
          - "7474:7474"
          - "7687:7687"
    eidetic:
        build: ../
        volumes:
          - ../:/app
        ports:
          - "8080:5000"