version: "3"

services:
    eidetic-gdb:
        image: neo4j:latest
        ports:
          - "7474:7474"
          - "7687:7687"
    eidetic:
        build: ../
        volumes:
          - ../:/app
        ports:
          - "8080:5000"
        environment:
          NEO4J_HOST: bolt://eidetic-gdb:7687
          NEO4J_USERNAME: ${NEO4J_USERNAME}
          NEO4J_PASSWORD: ${NEO4J_PASSWORD}
        depends_on:
          - eidetic-gdb
        command: /bin/bash -c "pwd && .docker/wait-for-it.sh -h eidetic-gdb -p 7687 && python app.py"