# System variable used to define temporary directory
# please update tmp_dir variable if needed
tmp_dir: /tmp/build
build_dir: "{{ tmp_dir }}/{{ inventory_hostname }}/tmp"
junos_conf: "config/{{ inventory_hostname }}.conf"

underlay:
  mtu_phy_int: 1600
  mtu_logical_int: 1500
